name: cached_network_image_web
description: Web implementation of CachedNetworkImage
version: 1.3.1
homepage: https://github.com/Baseflow/flutter_cached_network_image

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  cached_network_image_platform_interface: ^4.1.1
  flutter:
    sdk: flutter
  flutter_cache_manager: #  ^3.4.1 等3.4.2看看有没有改变   pub.dev内的版本有此问题 https://github.com/Baseflow/flutter_cache_manager/issues/476
    git:
      url: https://github.com/Baseflow/flutter_cache_manager.git
      ref: 54904e499a06d0364a2b3f4ca9789e5f829f1879
      path: flutter_cache_manager # 指定仓库内子路径
  web: ^1.0.0

dev_dependencies:
  file: '>=7.0.0 <8.0.0'
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
