name: cached_network_image
description: Flutter library to load and cache network images.
  Can also be used with placeholder and error widgets.
homepage: https://github.com/Baseflow/flutter_cached_network_image
topics:
  - cache
  - image
  - network-image
version: 3.4.1

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  cached_network_image_platform_interface: 
    git: 
      url: git@github.com:syt2/flutter_cached_network_image.git
      path: cached_network_image_platform_interface
  cached_network_image_web: 
    git: 
      url: git@github.com:syt2/flutter_cached_network_image.git
      path: cached_network_image_web
  flutter:
    sdk: flutter
  flutter_cache_manager: #  ^3.4.1 等3.4.2看看有没有改变   pub.dev内的版本有此问题 https://github.com/Baseflow/flutter_cache_manager/issues/476
    git:
      url: https://github.com/Baseflow/flutter_cache_manager.git
      ref: 54904e499a06d0364a2b3f4ca9789e5f829f1879
      path: flutter_cache_manager # 指定仓库内子路径
  octo_image: ^2.1.0

dev_dependencies:
  file: '>=7.0.0 <8.0.0'
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
